export const REQUEST_STATUS = {
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CONVERTED_TO_PROJECT: 'CONVERTED_TO_PROJECT',
  CLOSED: 'CLOSED',
};
export const REQUEST_STATUS_VALUES = Object.values(REQUEST_STATUS);

export const REQUEST_STATUS_FLOW = {
  [REQUEST_STATUS.NEW]: [REQUEST_STATUS.UNDER_REVIEW, REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CLOSED],
  [REQUEST_STATUS.UNDER_REVIEW]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED, REQUEST_STATUS.CLOSED],
  [REQUEST_STATUS.APPROVED]: [REQUEST_STATUS.CONVERTED_TO_PROJECT, REQUEST_STATUS.CLOSED],
  [REQUEST_STATUS.REJECTED]: [REQUEST_STATUS.CLOSED, REQUEST_STATUS.UNDER_REVIEW],
  [REQUEST_STATUS.CONVERTED_TO_PROJECT]: [REQUEST_STATUS.CLOSED],
  [REQUEST_STATUS.CLOSED]: [],
};

export const PROJECT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CLIENT: 'WAITING_FOR_CLIENT',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};
export const PROJECT_STATUS_VALUES = Object.values(PROJECT_STATUS);

export const PROJECT_STATUS_FLOW = {
  [PROJECT_STATUS.NOT_STARTED]: [PROJECT_STATUS.ASSIGNED, PROJECT_STATUS.IN_PROGRESS, PROJECT_STATUS.CANCELLED],
  [PROJECT_STATUS.ASSIGNED]: [PROJECT_STATUS.IN_PROGRESS, PROJECT_STATUS.NOT_STARTED, PROJECT_STATUS.CANCELLED],
  [PROJECT_STATUS.IN_PROGRESS]: [
    PROJECT_STATUS.WAITING_FOR_CLIENT,
    PROJECT_STATUS.UNDER_REVIEW,
    PROJECT_STATUS.CANCELLED,
  ],
  [PROJECT_STATUS.WAITING_FOR_CLIENT]: [
    PROJECT_STATUS.IN_PROGRESS,
    PROJECT_STATUS.UNDER_REVIEW,
    PROJECT_STATUS.REVISION_REQUIRED,
    PROJECT_STATUS.COMPLETED,
    PROJECT_STATUS.CANCELLED,
  ],
  [PROJECT_STATUS.UNDER_REVIEW]: [
    PROJECT_STATUS.REVISION_REQUIRED,
    PROJECT_STATUS.WAITING_FOR_CLIENT,
    PROJECT_STATUS.COMPLETED,
    PROJECT_STATUS.CANCELLED,
  ],
  [PROJECT_STATUS.REVISION_REQUIRED]: [PROJECT_STATUS.IN_PROGRESS, PROJECT_STATUS.CANCELLED],
  [PROJECT_STATUS.COMPLETED]: [],
  [PROJECT_STATUS.CANCELLED]: [],
};

export const PROJECT_STATUS_BY_ROLE = {
  ADMIN: PROJECT_STATUS_VALUES,
  STAFF: [PROJECT_STATUS.IN_PROGRESS, PROJECT_STATUS.WAITING_FOR_CLIENT, PROJECT_STATUS.UNDER_REVIEW],
  CLIENT: [],
};

export const ACTIVE_PROJECT_STATUSES = [
  PROJECT_STATUS.NOT_STARTED,
  PROJECT_STATUS.ASSIGNED,
  PROJECT_STATUS.IN_PROGRESS,
  PROJECT_STATUS.WAITING_FOR_CLIENT,
  PROJECT_STATUS.UNDER_REVIEW,
  PROJECT_STATUS.REVISION_REQUIRED,
];

export const ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED',
};
export const ASSIGNMENT_STATUS_VALUES = Object.values(ASSIGNMENT_STATUS);

export const REVISION_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};
export const REVISION_STATUS_VALUES = Object.values(REVISION_STATUS);

export const PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};
export const PRIORITY_VALUES = Object.values(PRIORITY);

export const SERVICE_TYPES = [
  'WEB_DEVELOPMENT',
  'MOBILE_APP',
  'UI_UX_DESIGN',
  'GRAPHIC_DESIGN',
  'CONTENT_WRITING',
  'SEO',
  'DIGITAL_MARKETING',
  'CONSULTING',
  'MAINTENANCE',
  'OTHER',
];
